# Generated by Django 2.2.12 on 2020-05-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='shipping_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shippingInfo'),
        ),
    ]
