# Generated by Django 2.2.12 on 2020-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200513_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='save',
            field=models.FloatField(default=20),
        ),
    ]
