# Generated by Django 2.2.12 on 2020-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200513_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='save',
            field=models.FloatField(),
        ),
    ]
