# Generated by Django 2.2.12 on 2020-05-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200513_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='save',
            new_name='saved',
        ),
    ]
