# Generated by Django 2.2.12 on 2020-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200513_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.IntegerField(default=1),
        ),
    ]
