# Generated by Django 2.2.12 on 2020-05-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='list_number',
            field=models.CharField(default='abc123', max_length=20),
            preserve_default=False,
        ),
    ]
