# Generated by Django 3.0.6 on 2020-05-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataView',
        ),
        migrations.CreateModel(
            name='DataView',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Summary',
                'verbose_name_plural': 'Sales Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.item',),
        ),
    ]
