# Generated by Django 3.0.6 on 2020-05-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200519_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataView',
        ),
    ]
