# Generated by Django 3.0.6 on 2020-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_image',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='intro_image',
            field=models.ManyToManyField(to='core.item_image'),
        ),
    ]
