# Generated by Django 3.0.6 on 2020-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200521_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
