# Generated by Django 3.0.6 on 2020-05-22 09:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200521_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_images',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[900, 600], upload_to=''),
        ),
    ]
