# Generated by Django 3.0.6 on 2020-05-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200522_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_images',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
