# Generated by Django 3.0.6 on 2020-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200522_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_images',
            name='mentioned_item',
            field=models.ManyToManyField(blank=True, to='core.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='intro_image',
            field=models.ManyToManyField(blank=True, to='core.item_image'),
        ),
    ]
