# Generated by Django 3.0.6 on 2020-05-22 11:21

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200522_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_images',
            name='mentioned_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='intro_image',
        ),
        migrations.CreateModel(
            name='intro_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[900, 600], upload_to='')),
                ('att_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_image', to='core.Item')),
            ],
        ),
    ]
