# Generated by Django 3.0.6 on 2020-05-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200522_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item_image',
        ),
    ]
