# Generated by Django 3.0.6 on 2020-05-23 12:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200523_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro_images',
            name='intro',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[240, 180], upload_to=''),
        ),
    ]
