# Generated by Django 3.0.6 on 2020-05-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200523_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_images',
            name='att_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_img', to='core.Item'),
        ),
    ]
